spring.application.name=cvr-backend

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}

external.api.key=${API_KEY}

spring.flyway.enabled=true

server.port=${PORT:8080}

rate.limit.requests-per-minute=10